language: cpp
sudo: false
dist: trusty
matrix:
  include:
  - os: linux
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++"
  - os: linux
    env:
      - MATRIX_EVAL="CXX_COMPILER=clang++"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++-5"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++-7"
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
    env:
      - MATRIX_EVAL="CXX_COMPILER=clang++-4.0"
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - MATRIX_EVAL="CXX_COMPILER=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls
  - ./install-gtest.sh
  - echo "CXX := ${CXX_COMPILER}" > local.mk
script: make all_tests -j
after_success:
  - coveralls --exclude gtest --exclude-pattern .*_test.cc --gcov-options '\-lp'