language: cpp
sudo: false
dist: trusty
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++-5"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CXX_COMPILER=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls
  - ./install-gtest.sh
  - echo "CXX := ${CXX_COMPILER}" > local.mk
script: make -j
after_success:
  - coveralls --exclude gtest --exclude-pattern .*_test.cc --gcov-options '\-lp'